// node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine, it allows developers to run JavaScript code outside of a web browser, it is commonly used for building server-side applications and APIs, it provides a non-blocking, event-driven architecture that makes it well-suited for building scalable and high-performance applications, it has a large ecosystem of libraries and frameworks that can be easily installed using the npm package manager, it is widely used in the industry and has a large community of developers who contribute to its development and maintenance.
// express.js helps to create a server and handle HTTP requests and responses, it is a popular framework for building web applications and APIs, it provides a simple and flexible way to handle routing, middleware, and other common web development tasks, it is built on top of Node.js and uses its event-driven, non-blocking I/O model to provide high performance and scalability, it is widely used in the industry and has a large community of developers who contribute to its development and maintenance.
//on the server side of backend, it uses express.js which is a minimal and flexible framework of node.js
//express.js gives us the freedom to structure your application the way you want it
//middleware is a function that has access to the request and response objects and the next function in the application's request-response cycle, it can execute any code, make changes to the request and response objects, end the request-response cycle, or call the next middleware function in the stack, it is used to perform tasks such as logging, authentication, error handling, and more, it allows developers to modularize their code and to reuse common functionality across different routes and endpoints in their application. it helps you handle the request response cycle and to manage the flow of data between the client and the server, it also allows for better organization and management of the codebase, making it easier to track changes and identify issues.
// the request - response side is the request client sends to the server and the response is what the server sends back to the client, it is important to understand the request-response cycle when building web applications and APIs, it allows developers to handle incoming requests and to send appropriate responses back to the client, it also allows for better organization and management of the codebase, making it easier to track changes and identify issues.
//express.js is built on top of Node.js and uses its event-driven, non-blocking I/O model to provide high performance and scalability, it is widely used in the industry and has a large community of developers who contribute to its development and maintenance.
//next.js is for backend end development, it is a popular framework for building server-rendered React applications, it provides a simple and flexible way to handle routing, server-side rendering, and other common web development tasks, it is built on top of React and uses its component-based architecture to provide a powerful and efficient way to build user interfaces, it is widely used in the industry and has a large community of developers who contribute to its development and maintenance.
// nest.js is a framework for building efficient, scalable Node.js server-side applications, it is built on top of Express.js and uses its features to provide a powerful and flexible way to handle routing, middleware, and other common web development tasks, it is built using TypeScript and uses decorators and other features of TypeScript to provide a more structured and organized way to build applications, it is widely used in the industry and has a large community of developers who contribute to its development and maintenance.
//api stands for Application Programming Interface, it is a set of rules and protocols that allows different software applications to communicate with each other, it defines how requests and responses should be formatted and what actions can be performed on the data, it is commonly used in web development to allow different applications to interact with each other over the internet, it can be used to access data from a database, to perform operations on a server, or to integrate with third-party services, it is an essential part of modern web development and is widely used in the industry.
//api is a set of rules and protocols that allows different software applications to communicate with each other, it defines how requests and responses should be formatted and what actions can be performed on the data, it is commonly used in web development to allow different applications to interact with each other over the internet, it can be used to access data from a database, to perform operations on a server, or to integrate with third-party services, it is an essential part of modern web development and is widely used in the industry.
//api is an essential part of modern web development and is widely used in the industry, it allows developers to create powerful and flexible applications that can interact with other applications and services, it also allows for better organization and management of the codebase, making it easier to track changes and identify issues.
//api is the middle man between two systems; it can be a backend and a backend, an api to an api, or a backend to a frontend, or a client to a server
//backend to backend is when one backend service communicates with another backend service, this can be done using APIs, it allows for better organization and management of the codebase, making it easier to track changes and identify issues, it also allows for better scalability and performance by allowing different services to handle different tasks and to communicate with each other as needed.
//api to api is when one API communicates with another API, this can be done using APIs, it allows for better organization and management of the codebase, making it easier to track changes and identify issues, it also allows for better scalability and performance by allowing different services to handle different tasks and to communicate with each other as needed.
//backend to frontend is when a backend service communicates with a frontend application, this can be done using APIs, it allows for better organization and management of the codebase, making it easier to track changes and identify issues, it also allows for better scalability and performance by allowing different services to handle different tasks and to communicate with each other as needed.
//client to server is when a client application communicates with a server application, this can be done using APIs, it allows for better organization and management of the codebase, making it easier to track changes and identify issues, it also allows for better scalability and performance by allowing different services to handle different tasks and to communicate with each
//restful api is an architectural style for building web services, it is based on the principles of Representational State Transfer (REST), it uses HTTP methods (such as GET, POST, PUT, DELETE) to perform operations on resources, it is stateless, meaning that each request from a client to a server must contain all the information needed to understand and process the request, it is widely used in the industry and has become a standard for building web APIs.
//resful api communicates to the front end applications or mobile client
//server side rendered web applications are those that are rendered on the server and sent to the client as a complete HTML document, this allows for faster initial load times and better SEO, it is commonly used in web development to create dynamic and interactive web applications, it can be built using frameworks such as Next.js, it is widely used in the industry and has a large community of developers who contribute to its development and maintenance.
//backend microservices in larger distributed systems uses express.js
//backend micriservices is raking your backend into differnet parts so they can work independently and codependently(like when you can add to cart but cant pay, shows that the backend part holding the add to cart is working well but the payment one isnt), microservices makes sure that if one part isnt working others can
//to install express, you need node js and npm. nmp comes with node js
//npm is the package manager for node.js, it allows you to install,update and manage libraries
//libraries are a collection of pre-written and usable codes that are installed an imported into your program to make your work faster.
//package.json file is a file that holds information about your project and its dependencies, it is created when you run npm init command, it allows you to manage your project's dependencies and scripts, it also allows other developers to understand the structure and requirements of your project when they want to contribute or use your code.

//to create a server using express.js, you need to first install express using npm, then you can create a new file (e.g. server.js) and require the express module, you can then create an instance of the express application and use it to define routes and middleware, finally you can start the server by calling the listen method on the express application instance
// to create a server using express.js, you need to first install express using npm, then you can create a new file (e.g. server.js) and require the express module, you can then create an instance of the express application and use it to define routes and middleware, finally you can start the server by calling the listen method on the express application instance
// to create this server use this command; nmp init - y (this creates a package.json file), then npm install express (this installs express and adds it to the dependencies in package.json), then create a new file (e.g. server.js) and adds some code
//if you run nmp init on your terminal , it will walk you through creating a package.json file, it will ask you for the name of your project, version, description, entry point, test command, git repository, keywords, author and license. you can fill in the information or just press enter to use the default values. once you have completed the process, a package.json file will be created in your project directory with the information you provided.
//create a file named server.js and add the following code:
//then in your terminal write npm install express to install express and add it to the dependencies in package.json, then you can run the server using node server.js command in your terminal, this will start the server and you can access it by going to http://localhost:3000 in your web browser.
//every express.js follows the following, installing express by running npm install express using requie[], create an app by calling express(), define routes and middleware, and start the server by calling the listen method on the express application instance, then define routine and lastly start listening to the server.
//to impory express use const express(or the name you want) = require('express')
//to create an express application instance of the express application use const app = express(). this is creating a copy of the express module that you can use to define routes and middleware, it is the main object that you will use to interact with the express framework and to build your application. in short it is the creation of a copy of express module
//to define a route use app.get('/', (req, res) => { res.send('Hello World!') })
//to start the server use app.listen(3000, () => { console.log('Server is running on port 3000') })
//(you can refer tp the TECH-CRUSH(SERVER-SIDE)) folder for the full code of the server.js file)
//following these steps will allow you to create a basic server using express.js, you can then add more routes and middleware as needed to build your application.
//you can name your portnumber anything you want, but it is common to use port 3000 for development purposes, you can choose any available port number that is not being used by another application on your machine. when you start the server, it will listen for incoming requests on the specified port, and you can access it by going to http://localhost:PORT_NUMBER in your web browser, where PORT_NUMBER is the port number you chose when starting the server. it could be 3000, 8080, or any other available port number. it is important to choose a port number that is not being used by another application on your machine to avoid conflicts and ensure that your server can run properly.

//running the server run: node server.js. this opens a browser and goes to http://localhost:3000, you should see the message "Hello World!" displayed on the page, this means that your server is running and is able to handle incoming requests and send appropriate responses back to the client. you can also test your server using tools like Postman or curl to send different types of requests and see how your server responds.
//to view what you did on your browser, run localhost:3000(or the port number you chose) in your web browser, this will send a request to your server and you should see the response that you defined in your route (e.g. "Hello World!"). if you see the message displayed on the page, it means that your server is running and is able to handle incoming requests and send appropriate responses back to the client. you can also test your server using tools like Postman or curl to send different types of requests and see how your server responds