//a database is an organized collection of data, stored and accessed electronically. It allows you to store, manage and retrive data efficiently. Its like a digital filing cabinet where each drawer represents a specific type of data and you can easily open any drawer to access the information you need. There are different types of databases such as relational databases, NoSQL databases, and in-memory databases. Each type has its own advantages and use cases. For example, relational databases are great for structured data and complex queries, while NoSQL databases are better for unstructured data and scalability. In backend development, we often use databases to store user information, product details, and other data that our application needs to function properly. It is important to choose the right database for your application based on your specific requirements and use case.
//table is a collection of related data organized in rows and columns. It is a fundamental component of a relational database. Each row in a table represents a single record, while each column represents a specific attribute or field of the record. For example, in a table called "users", each row would represent a single user, and the columns might include attributes such as "id", "name", "email", and "password". Tables allow us to store and organize data in a structured way, making it easier to query and manage the information stored in the database. In backend development, we often create tables to store different types of data that our application needs to function properly. it contains rows and columns. rows are called records and columns are called fields. each record contains specific information about an entity. for example, in a table called "users", each record would represent a single user and would contain fields such as "id", "name", "email", and "password". tables allow us to store and manage data in a structured way, making it easier to retrieve and manipulate the information as needed. in backend development, we often work with tables to perform various operations such as creating, reading, updating, and deleting data in our databases.
//record is a single entry in a table that contains specific information about an entity. It is represented as a row in a table and consists of multiple fields or attributes that describe the entity. For example, in a table called "users", each record would represent a single user and would contain fields such as "id", "name", "email", and "password". Records allow us to store and manage individual pieces of data within a table, making it easier to retrieve and manipulate the information as needed. In backend development, we often work with records to perform various operations such as creating, reading, updating, and deleting data in our databases.
//rows are called records and columns are called fields. each record contains specific information about an entity. for example, in a table called "users", each record would represent a single user and would contain fields such as "id", "name", "email", and "password". tables allow us to store and manage data in a structured way, making it easier to retrieve and manipulate the information as needed. in backend development, we often work with tables to perform various operations such as creating, reading, updating, and deleting data in our databases.. it represnets a record
//columns are called fields. each record contains specific information about an entity. for example, in a table called "users", each record would represent a single user and would contain fields such as "id", "name", "email", and "password". tables allow us to store and manage data in a structured way, making it easier to retrieve and manipulate the information as needed. in backend development, we often work with tables to perform various operations such as creating, reading, updating, and deleting data in our databases.. it represents a field or attribute of a record. each column it represents a specific field of data
//database management system (DBMS) is software that allows you to create, manage and interact with databases. It provides an interface for users to interact with the database and perform various operations such as creating tables, inserting data, querying data, and managing the database structure. Some popular DBMS include MySQL, PostgreSQL, MongoDB, and SQLite. Each DBMS has its own features and capabilities, so it is important to choose the right one for your application based on your specific needs and requirements. In backend development, we often use a DBMS to manage our databases and ensure that our application can efficiently store and retrieve data as needed.

//types
//relational databases(SQL): it stores data in structured tables with predefined relationships. each coloumn has its identity and data type. it uses SQL to query and manipulate data. it is great for structured data and complex queries. examples include MySQL, PostgreSQL, and SQLite. eg imagine an online library system, where one table stores books details and another stores information aout borrowers. a relational database can link these two
//NoSQL databases: they are none tabular and can handle a variety of data types. data is stored in a document. they are more flexible than nosql. it stores data in a non-relational format, such as key-value pairs, documents, or graphs. it is more flexible and scalable than relational databases. it is great for unstructured data and large volumes of data. examples include MongoDB, Cassandra, and Redis. examples are social media applications since they often use NOSQL database to store unstructured data like posts, comments and user profile
//in-memory databases: it stores data in the main memory (RAM) instead of on disk. it provides faster access to data compared to traditional disk-based databases. it is great for caching and real-time applications. examples include Redis and Memcached.

//comparison
//sql is structured and organized (eg banking system), nosql is unstructured and flexible (eg social media)

//roles
//data storage, retrival and integrity(consistency)

//database save informations on a disk or in the cloud and when you need information, you make a request called a query. this allows the system to retrieve the data
//the CRUD operations (Create, Read, Update and Delete), 
//install cors on your terminal by typing npm install cors


//http status code are three digit numbers returned by the server in the response. they tell the client whether the request was successful, redirected, or caused an error. always set the correct status code. it is part of the API contract
//2xx - success: 200 Ok (standard success rsponse. used for GET, PUT, PATCH, and DELETE), 201created (resource was successfully created.use after a successful POST), 204 No Content(success but no data to return, common after s DELETE operation)
//4xx - Client Errors: 400 Bad Request (the request was malformed or missing required fields), 404 unauthorized (authentication is required but was not provided or is invalid), 403 forbidden (authenticated but not permitted)


// assignment:write aboust the entire series of the http code, pick 2 from 100 - 500 each (talk about each of the types you picked )